/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('etkfront.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'etkfront.view.MyViewportViewModel',
        'etkfront.view.MyViewportViewController',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.TextArea',
        'Ext.form.field.Display',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean'
    ],

    controller: 'myviewport',
    viewModel: {
        type: 'myviewport'
    },
    height: 250,
    width: 400,
    layout: 'border',

    items: [
        {
            xtype: 'tabpanel',
            region: 'center',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: 'Физическое лицо',
                    items: [
                        {
                            xtype: 'container',
                            height: 150,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'textfield',
                                    reference: 'flpin',
                                    fieldLabel: 'ПИН ФЛ'
                                },
                                {
                                    xtype: 'textareafield',
                                    reference: 'token',
                                    maxHeight: 100,
                                    fieldLabel: 'Token'
                                },
                                {
                                    xtype: 'textareafield',
                                    reference: 'refresh',
                                    maxHeight: 100,
                                    fieldLabel: 'RenewToken'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Получить',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: 'обновить',
                                    listeners: {
                                        click: 'onButtonClick1'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 496,
                                    title: 'Полная детальная информация по ТК',
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            reference: 'work',
                                            width: 418,
                                            fieldLabel: 'Label',
                                            value: 'Display Field'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'mybutton1',
                                            text: 'Получить',
                                            listeners: {
                                                click: 'onMybuttonClick1'
                                            }
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            store: 'works',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'id_lc',
                                                    text: 'Уникальный идентификатор в LC'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'parent_id_lc',
                                                    text: 'Родительская запись'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'active_lc',
                                                    text: 'Активность ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'datetime_lc',
                                                    text: 'Дата создания записи'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'daterange_lc',
                                                    text: 'Диапазон действия ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'type_lc',
                                                    text: 'Тип записи (Трудовая деятельность, Образование, Военная служба)'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'direct_lc',
                                                    text: 'Направление записи ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'edit_id_lc',
                                                    text: 'Редактируемая запись'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'pin_lc',
                                                    text: 'ПИН ФЛ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'taxper_lc',
                                                    text: 'ИНН ФЛ в ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'passport_lc',
                                                    text: 'Паспорт'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'familyperson_lc',
                                                    text: 'Фамилия'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'nameperson_lc',
                                                    text: 'Имя'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'midlenameperson_lc',
                                                    text: 'Отчество'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'tin_lc',
                                                    text: 'ИНН ЮЛ в ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'name_lc',
                                                    text: 'Наименование ЮЛ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'oked_lc',
                                                    text: 'ОКЭД в ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'regionent_lc',
                                                    text: 'СОАТО ЮЛ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'department_lc',
                                                    text: 'Подразделение ЮЛ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'position_lc',
                                                    text: 'Должность'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'prof_lc',
                                                    text: 'Код профессии, должности'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'id_position',
                                                    text: 'Уникальный идентификатор должности'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'salary_lc',
                                                    text: 'Зарплата'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'flagbonus_lc',
                                                    text: 'Признак надбавка'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'termsalaru_lc',
                                                    text: 'Условия оплаты труда'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'typeemp_lc',
                                                    text: 'Вид занятости ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'codenskz_lc',
                                                    text: 'Код по НСКЗ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'order_lc',
                                                    text: 'Приказ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'dateorder_lc',
                                                    text: 'Дата приказа'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'article_lc',
                                                    text: 'Статья'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'specspo_lc',
                                                    text: 'Учебная специальность СПО'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'codespo_ls',
                                                    text: 'Код специальности СПО'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'specvo_ls',
                                                    text: 'Учебная специальность ВО'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'codevo_ls',
                                                    text: 'Код специальности ВО'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'acceptemployer_lc',
                                                    text: 'Подтверждение работодателя'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'acceptemployee_lc',
                                                    text: 'Подтверждение работника'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'warehouse_id',
                                                    text: 'Идентификатор записи в Хранилище'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'value_fields_lc',
                                                    text: 'Значения полей ТД'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    height: 451,
                                    title: 'Обобщенная информация по трудовой',
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            reference: 'errors',
                                            width: 418,
                                            fieldLabel: 'Label',
                                            value: 'Display Field'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'mybutton',
                                            text: 'Получить',
                                            listeners: {
                                                click: 'onMybuttonClick'
                                            }
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            store: 'works',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'id_lc',
                                                    text: 'Уникальный идентификатор в LC'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'parent_id_lc',
                                                    text: 'Родительская запись'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'active_lc',
                                                    text: 'Активность ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'datetime_lc',
                                                    text: 'Дата создания записи'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'daterange_lc',
                                                    text: 'Диапазон действия ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'type_lc',
                                                    text: 'Тип записи (Трудовая деятельность, Образование, Военная служба)'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'direct_lc',
                                                    text: 'Направление записи ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'edit_id_lc',
                                                    text: 'Редактируемая запись'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'pin_lc',
                                                    text: 'ПИН ФЛ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'taxper_lc',
                                                    text: 'ИНН ФЛ в ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'passport_lc',
                                                    text: 'Паспорт'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'familyperson_lc',
                                                    text: 'Фамилия'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'nameperson_lc',
                                                    text: 'Имя'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'midlenameperson_lc',
                                                    text: 'Отчество'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'tin_lc',
                                                    text: 'ИНН ЮЛ в ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'name_lc',
                                                    text: 'Наименование ЮЛ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'oked_lc',
                                                    text: 'ОКЭД в ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'regionent_lc',
                                                    text: 'СОАТО ЮЛ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'department_lc',
                                                    text: 'Подразделение ЮЛ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'position_lc',
                                                    text: 'Должность'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'prof_lc',
                                                    text: 'Код профессии, должности'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'id_position',
                                                    text: 'Уникальный идентификатор должности'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'salary_lc',
                                                    text: 'Зарплата'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'flagbonus_lc',
                                                    text: 'Признак надбавка'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'termsalaru_lc',
                                                    text: 'Условия оплаты труда'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'typeemp_lc',
                                                    text: 'Вид занятости ТД'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'codenskz_lc',
                                                    text: 'Код по НСКЗ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'order_lc',
                                                    text: 'Приказ'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'dateorder_lc',
                                                    text: 'Дата приказа'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'article_lc',
                                                    text: 'Статья'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'specspo_lc',
                                                    text: 'Учебная специальность СПО'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'codespo_ls',
                                                    text: 'Код специальности СПО'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'specvo_ls',
                                                    text: 'Учебная специальность ВО'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'codevo_ls',
                                                    text: 'Код специальности ВО'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'acceptemployer_lc',
                                                    text: 'Подтверждение работодателя'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'acceptemployee_lc',
                                                    text: 'Подтверждение работника'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'warehouse_id',
                                                    text: 'Идентификатор записи в Хранилище'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'value_fields_lc',
                                                    text: 'Значения полей ТД'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Юридическое лицо',
                    items: [
                        {
                            xtype: 'container',
                            height: 150,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'textfield',
                                    reference: 'pinju',
                                    fieldLabel: 'ПИН ФЛ'
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'tinju',
                                    fieldLabel: 'ИНН ЮЛ'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'СОАТО'
                                },
                                {
                                    xtype: 'textareafield',
                                    reference: 'tokenju',
                                    height: 100,
                                    fieldLabel: 'Token'
                                },
                                {
                                    xtype: 'textareafield',
                                    reference: 'refreshju',
                                    height: 100,
                                    fieldLabel: 'RenewToken'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Получить',
                                    listeners: {
                                        click: 'onButtonClick2'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: 'обновить',
                                    listeners: {
                                        click: 'onButtonClick11'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Структура организации',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Список должностей',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Список сотрудников на дату',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Активные трудовые договоры',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Список своих пользователей',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Детализированная информация по ТК своего сотрудника',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Обощенная информация по ТК своего сотрудника',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Сотрудник МинЗТО',
                    items: [
                        {
                            xtype: 'container',
                            height: 150,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'ПИН ФЛ'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'ИНН ЮЛ'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'СОАТО'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'СОАТО МИНЗТО'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Token',
                                    value: 'Display Field'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'RenewToken',
                                    value: 'Display Field'
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Список всех своих организаций(структур)',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Список всех своих работающих по организации нах в его ведении(соато в иерархии) на конкретную дату',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Должности любой организации но из своего региона',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'пока все'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Супер Пользователь',
                    items: [
                        {
                            xtype: 'container',
                            height: 150,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'ПИН ФЛ'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'ПИН ФЛ'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'ПИН ФЛ'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'ПИН ФЛ'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Token',
                                    value: 'Display Field'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'RenewToken',
                                    value: 'Display Field'
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Справочник констант',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Справочник пользователей',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Лог журнал',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Коды ошибок',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Лог по записи',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'My Grid Panel',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'number',
                                                    text: 'Number'
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'date',
                                                    text: 'Date'
                                                },
                                                {
                                                    xtype: 'booleancolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});