/*
 * File: app/view/MyViewportViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('etkfront.view.MyViewportViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.myviewport',

    onButtonClick: function(button, e, eOpts) {
        var me = this;
        Ext.Ajax.request({
            url: 'https://etk.micros.uz/oauth/token',

            method: 'POST',

            params: {
                "grant_type" : "password",
                "client_id" : "15",
                "client_secret" : "Mfoam6h0VgoMPF6OxCKFi8GRRpanVcIAg0zHaufs",
                "username" : me.lookup('flpin').getValue(),
                "password" : "123456",
                "scope" : ""
            },

            success: function(response, opts) {
                me.lookup('token').setValue(JSON.parse(response.responseText).access_token);
                me.lookup('refresh').setValue(JSON.parse(response.responseText).refresh_token);
                Ext.Ajax.setDefaultHeaders({
                    Authorization : 'Bearer ' + JSON.parse(response.responseText).access_token
                });
            },

            failure: function(response, opts) {
                console.log(response);
            },

            callback: function(options, success, response){
                console.log(response);
            }
        });
    },

    onButtonClick1: function(button, e, eOpts) {
        var me = this;
        Ext.Ajax.request({
            url: 'https://etk.micros.uz/oauth/token',

            method: 'POST',

            params: {
                "grant_type" : "refresh_token",
                "client_id" : "15",
                "client_secret" : "Mfoam6h0VgoMPF6OxCKFi8GRRpanVcIAg0zHaufs",
                "refresh_token" : me.lookup('refresh').getValue(),
                "scope" : ""
            },

            success: function(response, opts) {
                me.lookup('token').setValue(JSON.parse(response.responseText).access_token);
                me.lookup('refresh').setValue(JSON.parse(response.responseText).refresh_token);
                Ext.Ajax.setDefaultHeaders({
                    Authorization : 'Bearer ' + JSON.parse(response.responseText).access_token
                });
            },

            failure: function(response, opts) {
                console.log(response);
            },

            callback: function(options, success, response){
                console.log(response);
            }
        });
    },

    onMybuttonClick1: function(button, e, eOpts) {
        Ext.getStore('works').load({params:{
            page:1
        }});
    },

    onMybuttonClick: function(button, e, eOpts) {
        var me = this;
        console.log(me);
        // Ext.Ajax.request({
        //     url: 'http://etkback/api/v1/errors',

        //     method: 'get',

        //     //    headers: {
        //     //      'Authorization': 'Bearer '+''
        //     //},

        //     success: function(response, opts) {
        //         me.lookup('errors').setValue(JSON.parse(response.responseText).data[0].ErrorList);
        //     },

        //     failure: function(response, opts) {
        //         console.log(response);
        //     },

        //     callback: function(options, success, response){
        //         console.log(response);
        //     }
        // });

        Ext.getStore('errors').load();
    },

    onButtonClick2: function(button, e, eOpts) {
        var me = this;
        Ext.Ajax.request({
            url: 'https://etk.micros.uz/oauth/token',

            method: 'POST',

            params: {
                "grant_type" : "password",
                "client_id" : "15",
                "client_secret" : "Mfoam6h0VgoMPF6OxCKFi8GRRpanVcIAg0zHaufs",
                "username" : me.lookup('pinju').getValue(),
                "user_tin_company" : me.lookup('tinju').getValue(),
                "password" : "123456",
                "scope" : ""
            },

            success: function(response, opts) {
                me.lookup('tokenju').setValue(JSON.parse(response.responseText).access_token);
                me.lookup('refreshju').setValue(JSON.parse(response.responseText).refresh_token);
                Ext.Ajax.setDefaultHeaders({
                    Authorization : 'Bearer ' + JSON.parse(response.responseText).access_token
                });
            },

            failure: function(response, opts) {
                console.log(response);
            },

            callback: function(options, success, response){
                console.log(response);
            }
        });
    },

    onButtonClick11: function(button, e, eOpts) {
        var me = this;
        Ext.Ajax.request({
            url: 'https://etk.micros.uz/oauth/token',

            method: 'POST',

            params: {
                "grant_type" : "refresh_token",
                "client_id" : "15",
                "client_secret" : "Mfoam6h0VgoMPF6OxCKFi8GRRpanVcIAg0zHaufs",
                "refresh_token" : me.lookup('refreshju').getValue(),
                "scope" : ""
            },

            success: function(response, opts) {
                me.lookup('tokenju').setValue(JSON.parse(response.responseText).access_token);
                me.lookup('refreshju').setValue(JSON.parse(response.responseText).refresh_token);
                Ext.Ajax.setDefaultHeaders({
                    Authorization : 'Bearer ' + JSON.parse(response.responseText).access_token
                });
            },

            failure: function(response, opts) {
                console.log(response);
            },

            callback: function(options, success, response){
                console.log(response);
            }
        });
    }

});
