/*
 * File: app/model/errors.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('etkfront.model.errors', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    proxy: {
        type: 'rest',
        url: 'https://etk.micros.uz/api/v1/errors',
        reader: {
            type: 'json',
            rootProperty: 'data.DATA',
            totalProperty: 'data.TOTAL'
        }
    }
});